package hibernate;
// Generated 17-mar-2015 10:55:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.json.JSONObject;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set productos = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(String nombre) {
        this.nombre = nombre;
    }
    public Categoria(String nombre, Set productos) {
       this.nombre = nombre;
       this.productos = productos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }
    
    public JSONObject getJSON(){
        JSONObject objetoJson = new JSONObject();
        objetoJson.put("id", this.id);
        objetoJson.put("nombre", this.nombre);
        return objetoJson;
    }




}


