package hibernate;
// Generated 17-mar-2015 10:55:46 by Hibernate Tools 4.3.1

import modelos.ModeloPedido;
import modelos.ModeloProducto;
import org.json.JSONObject;




/**
 * Lineapedido generated by hbm2java
 */
public class Lineapedido  implements java.io.Serializable {


     private Integer id;
     private Pedido pedido;
     private Producto producto;
     private Integer cantidad;

    public Lineapedido() {
    }

	
    public Lineapedido(Pedido pedido, Producto producto) {
        this.pedido = pedido;
        this.producto = producto;
    }
    public Lineapedido(Pedido pedido, Producto producto, Integer cantidad) {
       this.pedido = pedido;
       this.producto = producto;
       this.cantidad = cantidad;
    }
    
    public Lineapedido(JSONObject object){
       this.pedido = ModeloPedido.get(object.getInt("id_pedido")+"");
       this.producto = ModeloProducto.get(object.getInt("id_producto")+"");
       this.cantidad = object.getInt("cantidad");
       this.producto.setStock(this.producto.getStock() - this.cantidad);
       ModeloProducto.edit(producto);
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


