package hibernate;
// Generated 17-mar-2015 10:55:46 by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private String usuario;
     private String clave;

    public Login() {
    }

    public Login(String usuario, String clave) {
       this.usuario = usuario;
       this.clave = clave;
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }




}


