package hibernate;
// Generated 16-mar-2015 11:20:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer id;
     private Categoria categoria;
     private String titulo;
     private String descripcion;
     private BigDecimal precio;
     private Integer stock;
     private String imagen;
     private Set lineapedidos = new HashSet(0);

    public Producto() {
    }

	
    public Producto(Categoria categoria, String titulo, BigDecimal precio) {
        this.categoria = categoria;
        this.titulo = titulo;
        this.precio = precio;
    }
    public Producto(Categoria categoria, String titulo, String descripcion, BigDecimal precio, Integer stock, String imagen, Set lineapedidos) {
       this.categoria = categoria;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.precio = precio;
       this.stock = stock;
       this.imagen = imagen;
       this.lineapedidos = lineapedidos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Set getLineapedidos() {
        return this.lineapedidos;
    }
    
    public void setLineapedidos(Set lineapedidos) {
        this.lineapedidos = lineapedidos;
    }




}


